from publicnewsarchive.dataExtraction.PastURLs import getPastURLs
from publicnewsarchive.dataExtraction.NewsArticles import getNewsArticles
from publicnewsarchive.dataExtraction.NewsData import getNewsData